//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class AudioMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/Audio";
        public override string RosMessageName => k_RosMessageName;

        public float[] data;

        public AudioMsg()
        {
            this.data = new float[0];
        }

        public AudioMsg(float[] data)
        {
            this.data = data;
        }

        public static AudioMsg Deserialize(MessageDeserializer deserializer) => new AudioMsg(deserializer);

        private AudioMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "AudioMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
