//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class JointsToTargetMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/JointsToTarget";
        public override string RosMessageName => k_RosMessageName;

        public int[] joints;
        public float[] targets;

        public JointsToTargetMsg()
        {
            this.joints = new int[0];
            this.targets = new float[0];
        }

        public JointsToTargetMsg(int[] joints, float[] targets)
        {
            this.joints = joints;
            this.targets = targets;
        }

        public static JointsToTargetMsg Deserialize(MessageDeserializer deserializer) => new JointsToTargetMsg(deserializer);

        private JointsToTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.targets, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.joints);
            serializer.Write(this.joints);
            serializer.WriteLength(this.targets);
            serializer.Write(this.targets);
        }

        public override string ToString()
        {
            return "JointsToTargetMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\ntargets: " + System.String.Join(", ", targets.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
