//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class PosEyelidsMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/PosEyelids";
        public override string RosMessageName => k_RosMessageName;

        public float pos_up;
        public float pos_down;

        public PosEyelidsMsg()
        {
            this.pos_up = 0.0f;
            this.pos_down = 0.0f;
        }

        public PosEyelidsMsg(float pos_up, float pos_down)
        {
            this.pos_up = pos_up;
            this.pos_down = pos_down;
        }

        public static PosEyelidsMsg Deserialize(MessageDeserializer deserializer) => new PosEyelidsMsg(deserializer);

        private PosEyelidsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pos_up);
            deserializer.Read(out this.pos_down);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos_up);
            serializer.Write(this.pos_down);
        }

        public override string ToString()
        {
            return "PosEyelidsMsg: " +
            "\npos_up: " + pos_up.ToString() +
            "\npos_down: " + pos_down.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
